### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by abonsignore** [jvitor83/angular-pwa-seed#27] opened 2018-01-01 21:32 UTC
Interesting seed... thank you.

Getting the following error when running... npm install

npm WARN angular-pwa-seed@0.1.0 No repository field.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for asn1.js@4.10.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'angular-pwa-seed'
npm ERR! notarget

Any Ideas?
Thanks

**Comment by jvitor83** [comment] 2018-01-02 19:40
@abonsignore 
What Operation System are you using?
What your NodeJS version?
What your NPM version?

**Comment by abonsignore** [comment] 2018-01-02 20:53
Thanks for the quick response.
I actually use both Windows and OS X, but trying to install on Windows for now.

@ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:
    cordova (Cordova CLI) : 6.5.0

local packages:
    @ionic/app-scripts : not installed
    Cordova Platforms  : none
    Ionic Framework    : not installed

System:
    Android SDK Tools : 26.0.1
    Node              : v6.9.5
    npm               : 5.3.0
    OS                : Windows 10

Local packages are not installed because npm install doesn't finish.

Thanks.

**Comment by jvitor83** [comment] 2018-01-02 21:01
@abonsignore i just try the `npm install` on node v8.9.0 and npm 5.5.1. It works.
I think i need to update the readme to a newer version.
Can you try this on a node 8.x?

**Comment by abonsignore** [comment] 2018-01-02 22:03
Will have to try on a different box.

Thanks again for your time.

**Comment by jvitor83** [comment] 2018-01-03 01:53
@abonsignore 
I have tried with exactly the same version of nodejs you mention (v6.9.5) and cound't reproduce your error.
Then tried with the latest version too (v9.3.0) and it work just fine.
My guess is that something at your environment are wrong.
Will close this issue since cound't reproduce the behavior mentioned. Feel free to open again if discover something new about it.

**Closed as completed by jvitor83** 2018-01-03 01:53 UTC

**Comment by abonsignore** [comment] 2018-01-03 06:06
Problem Solved... for anyone that comes to this thread.
Removed file... package-lock.json and then "npm install" worked like a charm.

You may have to "npm cache clear --force" as well.

Thanks Again for your time and for trying to replicate my problem.
